Import('env')
Import('libs')

build_env = env.Clone()

env.Program(target='arraylist_unittest', source=['arraylist_unittest.cpp'], LIBS=libs)
env.Program(target='linkedlist_unittest', source=['linkedlist_unittest.cpp'], LIBS=libs)
