#include <string>
#include <iostream>

#define URANUS_SUCCESS 0

#define URANUS_UNKOWN_ERROR = -1

#define URANUS_INDEX_OUT_ARRAY -1000
#define URANUS_INDEX_LESS_THAN_ZERO -1001
#define URANUS_EMPTY_ARRAY -1002
#define URANUS_PREV_NULL -1003

#define URANUS_FIND_NOTHING -1004
#define URANUS_EMPTY_TREE -1005
